name: CI

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "9e593bb18ea69cc5095e012465dcd675a822ed0d"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-pc-windows-msvc, os: windows-2022 }

    steps:
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup vcpkg with Github Actions binary cache
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: /opt/artifacts/vcpkg
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

    - name: Install vcpkg dependencies and FIX Bindgen Paths
      shell: bash
      run: |
        $VCPKG_ROOT/vcpkg install --x-install-root="$VCPKG_ROOT/installed"
        
        # EL TRUCO DEFINITIVO: Forzar a clang/bindgen a encontrar Opus
        echo "BINDGEN_EXTRA_CLANG_ARGS=-I/opt/artifacts/vcpkg/installed/x64-windows-static/include" >> $GITHUB_ENV
        echo "INCLUDE=D:\\opt\\artifacts\\vcpkg\\installed\\x64-windows-static\\include;$INCLUDE" >> $GITHUB_ENV
        echo "LIB=D:\\opt\\artifacts\\vcpkg\\installed\\x64-windows-static\\lib;$LIB" >> $GITHUB_ENV

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: ${{ matrix.job.target }}
        components: ''

    - uses: Swatinem/rust-cache@v2

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: false
        command: build
        args: --locked --release --target=${{ matrix.job.target }}

    - name: Upload Windows EXE Artifact
      if: matrix.job.target == 'x86_64-pc-windows-msvc'
      uses: actions/upload-artifact@v4
      with:
        name: Soporte-PCCreative-Windows
        path: target/${{ matrix.job.target }}/release/*.exe